# This file will be used for simulating the model and performing analysis
using Pkg
Pkg.activate(joinpath(@__DIR__, "..", "..")) # activate the project environment, going up two directories from the current file location

# load in required packages
using DifferentialEquations, DataFrames, Plots # note we don't need Catalyst here as we already load it in the model_setup.jl file

# we need to load in the files which contain the variables we will use, another file we could have could be a file of functions but we don't have one here because the project is so simple
include("$(pwd())/ basic_intro/basic_project/params_init.jl") # pwd() gets the current working directory
include("$(pwd())/ basic_intro/basic_project/model_setup.jl")

tspan = (0.0, 200.0) # time span for the simulation

# define and solve the ODE problem
prob = ODEProblem(model, u0, tspan, params)
sol = solve(prob, Tsit5()) # Tsit5 is the solver

plot(sol) # plot should appear in a plot pane 

# check the ODEs generated by Catalyst.jl match our expectations
odesys = convert(ODESystem, model) # when using the REPL, latex equations don't appear automatically

# to see the equations in LaTeX format, we can use Latexify.jl
using Latexify
latexify(equations(odesys)) |> render # display the equations in LaTeX format